### ISSUE TITLE
IllegalModelAccessError when selecting over richtext word borders

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#300] opened 2020-06-19 19:05 UTC
In a `de.slisson.mps.richtext.structure.Word`, select characters by pressing `Shift-Right` or `Shift-Left`several times. When reaching the border to the next `de.slisson.mps.richtext.structure.Word`, the IllegalModelAccessError exception below is thrown.

Test environment: MPS 2020.1.1, MPS-extensions `2020.1.1430.367cc3b`.

```
2020-06-19 20:51:08,239 [ 338952]  ERROR - llij.ide.plugins.PluginManager - JetBrains MPS 2020.1  Build #MPS-201.6668.1353
2020-06-19 20:51:08,239 [ 338952]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-06-19 20:51:08,239 [ 338952]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X
2020-06-19 20:51:08,239 [ 338952]  ERROR - llij.ide.plugins.PluginManager - Last Action: jetbrains.mps.ide.editor.actions.SelectRight_Action
2020-06-19 20:51:08,385 [ 339098]  ERROR - .openapi.model.SNodeAccessUtil - jetbrains.mps.smodel.IllegalModelAccessError : You can read model only inside read actions
jetbrains.mps.smodel.IllegalModelAccessError: You can read model only inside read actions
	at jetbrains.mps.smodel.AbstractModelAccess.checkReadAccess(AbstractModelAccess.java:68)
	at jetbrains.mps.smodel.ModelAccessBase.checkReadAccess(ModelAccessBase.java:41)
	at jetbrains.mps.smodel.AttachedNodeOwner.assertLegalRead(AttachedNodeOwner.java:70)
	at jetbrains.mps.smodel.SNode.assertCanRead(SNode.java:113)
	at jetbrains.mps.smodel.SNode.getProperty(SNode.java:601)
	at jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor.getValue(BasePropertyConstraintsDescriptor.java:182)
	at jetbrains.mps.smodel.SNodeAccessUtilImpl.getPropertyValueImpl(SNodeAccessUtilImpl.java:79)
	at org.jetbrains.mps.openapi.model.SNodeAccessUtil.getPropertyValue(SNodeAccessUtil.java:43)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations.getString(SPropertyOperations.java:78)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.getText_idehGfXvI_DB(Word__BehaviorDescriptor.java:62)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.invokeSpecial0(Word__BehaviorDescriptor.java:169)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:358)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtualCommon(BaseBHDescriptor.java:306)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtual(BaseBHDescriptor.java:282)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:243)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.getTextLength_id635SBilAXnW(Word__BehaviorDescriptor.java:69)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.invokeSpecial0(Word__BehaviorDescriptor.java:174)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:358)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtualCommon(BaseBHDescriptor.java:306)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtual(BaseBHDescriptor.java:282)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:243)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.isValidCursorPosition_id635SBilAXqa(Word__BehaviorDescriptor.java:72)
	at de.slisson.mps.richtext.behavior.Word__BehaviorDescriptor.invokeSpecial0(Word__BehaviorDescriptor.java:176)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:358)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtualCommon(BaseBHDescriptor.java:306)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtual(BaseBHDescriptor.java:282)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:243)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at de.slisson.mps.richtext.runtime.selection.RichtextSelection.selectLeftRight(RichtextSelection.java:231)
	at de.slisson.mps.richtext.runtime.selection.RichtextSelection.executeAction(RichtextSelection.java:168)
	at jetbrains.mps.ide.editor.actions.SelectRight_Action.doExecute(SelectRight_Action.java:54)
	at jetbrains.mps.workbench.action.BaseAction.lambda$actionPerformed$2(BaseAction.java:186)
	at jetbrains.mps.workbench.action.ActionAccess$EmptyAccess.runWithAccess(ActionAccess.java:59)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:181)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:516)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:470)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-06-19 20:51:08,386 [ 339099]  ERROR - llij.ide.plugins.PluginManager - You can read model only inside read actions
jetbrains.mps.smodel.IllegalModelAccessError: You can read model only inside read actions
	at jetbrains.mps.smodel.AbstractModelAccess.checkReadAccess(AbstractModelAccess.java:68)
	at jetbrains.mps.smodel.ModelAccessBase.checkReadAccess(ModelAccessBase.java:41)
	at jetbrains.mps.smodel.AttachedNodeOwner.assertLegalRead(AttachedNodeOwner.java:70)
	at jetbrains.mps.smodel.SNode.assertCanRead(SNode.java:113)
	at jetbrains.mps.smodel.SNode.getParent(SNode.java:155)
	at jetbrains.mps.smodel.SNode.getParent(SNode.java:46)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.getNextSibling(SNodeOperations.java:283)
	at de.slisson.mps.richtext.runtime.selection.RichtextSelection.selectLeftRight(RichtextSelection.java:235)
	at de.slisson.mps.richtext.runtime.selection.RichtextSelection.executeAction(RichtextSelection.java:168)
	at jetbrains.mps.ide.editor.actions.SelectRight_Action.doExecute(SelectRight_Action.java:54)
	at jetbrains.mps.workbench.action.BaseAction.lambda$actionPerformed$2(BaseAction.java:186)
	at jetbrains.mps.workbench.action.ActionAccess$EmptyAccess.runWithAccess(ActionAccess.java:59)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:181)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:516)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:470)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
20
```

**Comment by alexanderpann** [comment] 2021-08-31 12:45
This issue seems to be fixed. I can't reproduce it and the necessary read lock is present. Can someone close this issue?

**Closed** 2021-08-31 19:38 UTC
Labels: bug
