### ISSUE TITLE
langvis: property doubling in classes and interfaces in UML diagram

### ISSUE THREAD

**Issue by Mr-Slippery** [JetBrains/MPS-extensions#386] opened 2021-04-25 16:17 UTC
There is an error in `langvis/solutions/com.dslfoundry.langvis.plugin` that is causing a doubling of properties in the rendered diagrams for both classes and interfaces:

<img width="1440" alt="Screenshot 2021-04-25 at 16 04 47" src="https://user-images.githubusercontent.com/5954346/116000781-e4d81580-a5f1-11eb-9579-cff2e4d6b2a0.png">

This should be fixed, and, as a result, the diagram (including also an interfaces in this case) should be rendered like this:

<img width="1440" alt="Screenshot 2021-04-25 at 17 32 04" src="https://user-images.githubusercontent.com/5954346/116000887-4bf5ca00-a5f2-11eb-88ef-cbefc03d8618.png">

Thanks a lot for your consideration!

**Comment by eugenschindler** [comment] 2021-04-26 15:39
Duplicate of #362

**Closed** 2021-04-29 10:35 UTC
Labels: bug, comp.langvis
