### ISSUE TITLE
Diagram: Palette doesn't work in floating mode

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#62] opened 2018-08-06 14:52 UTC
From mbeddr.core created by [slisson](https://github.com/slisson) : mbeddr/mbeddr.core#1810

**Comment by alexanderpann** [comment] 2023-03-21 15:51
I am closing this issue because this bug is not reproducible anymore.

**Closed by alexanderpann** 2023-03-21 15:51 UTC
Labels: comp.diagram
