### ISSUE TITLE
Could not initialize class com.mbeddr.mpsutil.modellisteners.runtime.plugin.IconContainer

### ISSUE THREAD

**Issue by cfuerbachersparks** [JetBrains/MPS-extensions#1007] opened 2024-11-07 14:14 UTC
I upgraded from the extensions in our project from `9999.9.2969.cbade73-20240912.194917-1` to `9999.9.3003.4ff035e-20241106.030219-1` as build 2969 is no longer available from the maven repository anymore. Now i get a `java.lang.NoClassDefFoundError` Exception and all Languages that have a modellistener aspect can't be loaded anymore. Here is a screenshot of the languages not loading.
![loadingLanguages](https://github.com/user-attachments/assets/314be4e7-836f-441d-850e-e29886a5424b)
Gradle can still successfully build the project and the modellisteners work with the resulting IDE and plugins.

I upgraded the extensions be deleting MPS and reinstalling it, then copy the plugins into the MPS/plugins folder. I also deleted and cloned the project i am working on so no files can be cached there.

I am using MPS 2024.1.1.
[idea.log](https://github.com/user-attachments/files/17662475/idea.log)

**Comment by alexanderpann** [comment] 2024-11-07 14:22
You probably have to wait for https://github.com/JetBrains/MPS-extensions/pull/1005 to be merged where we might have fixed it. I noticed it as well and this looks like a bug in MPS.

**Comment by sergej-koscejev** [comment] 2024-11-08 06:23
In MPS master, post-2024.1, there is an additional constructor in IconResource that is used by the generated code. If you load code that was built by MPS master in MPS 2024.1, you will get this error. This is not a bug in MPS.

As Alexander mentioned, we are creating a 2024.1 branch of MPS-extensions currently so this problem will be fixed in that branch simply due to the code being built by MPS 2024.1.

**Comment by alexanderpann** [comment] 2024-12-11 21:59
We now have a 2024.1 and 2024.3 branch, so this issue is obsolete.

**Closed by alexanderpann** 2024-12-11 21:59 UTC
