### ISSUE TITLE
Auto layout option moves the contents of boxes (it should not)

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#82] opened 2018-08-06 15:01 UTC
From mbeddr.core created by [joswarmer](https://github.com/joswarmer) : mbeddr/mbeddr.core#1467  

First click on "Fit size of All Boxes".   Then click on "Auto Layout Diagram".  The Auto layout action then changes the location of the contents inside the boxes in the diagram.  I was expecting that it would only re-layout the boxes, not their contents.

If I select a box after the re-layout, the box gets selected and its contents immediately moves back to the position after the "Fix Size of All boxes".  My guess is that the move of the contents after the re-layout is probably wrong.

**Comment by alexanderpann** [comment] 2024-06-18 20:22
I close the issue because it is not reproducible anymore. If the content moves back, the changes are probably not synced. This issue will be fixed in the branch https://github.com/JetBrains/MPS-extensions/tree/bugfix/diagram_edge_masking.

**Closed by alexanderpann** 2024-06-18 20:22 UTC
Labels: bug, comp.diagram
