### ISSUE TITLE
Remove usages of SNodeLegacy

### ISSUE THREAD

**Issue by slisson** [JetBrains/MPS-extensions#281] opened 2020-02-06 15:18 UTC
[ 694911] ERROR - tbrains.mps.smodel.SNodeLegacy - SNodeLegacy class is scheduled for removal, refactor your code
java.lang.Throwable
    at jetbrains.mps.smodel.SNodeLegacy.getRoleLink(SNodeLegacy.java:50)
    at de.slisson.mps.tables.runtime.cells.TableEditorActions$EnlargeSelection.findTopMostNodeWithSingularContainment(TableEditorActions.java:630)
    at de.slisson.mps.tables.runtime.cells.TableEditorActions$EnlargeSelection.execute(TableEditorActions.java:603)
    at jetbrains.mps.nodeEditor.actions.CellActionExecuter.lambda$execute$1(CellActionExecuter.java:54)
    at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:85)
    at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:791)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:82)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:54)
    at jetbrains.mps.nodeEditor.actions.CellActionExecuter.lambda$execute$2(CellActionExecuter.java:64)
    at jetbrains.mps.nodeEditor.EditorContext.lambda$runWithContextCell$3(EditorContext.java:269)
    at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:280)
    at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:268)
    at jetbrains.mps.nodeEditor.actions.CellActionExecuter.execute(CellActionExecuter.java:53)
    at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.executeAction(ActionHandlerImpl.java:41)
    at jetbrains.mps.nodeEditor.selection.EditorCellSelection.executeAction(EditorCellSelection.java:164)
    at jetbrains.mps.nodeEditor.selection.EditorCellLabelSelection.executeAction(EditorCellLabelSelection.java:171)
    at jetbrains.mps.ide.editor.actions.SelectPrevious_Action.doExecute(SelectPrevious_Action.java:54)
    at jetbrains.mps.workbench.action.BaseAction.lambda$actionPerformed$2(BaseAction.java:186)
    at jetbrains.mps.workbench.action.ActionAccess$EmptyAccess.runWithAccess(ActionAccess.java:59)
    at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:181)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:604)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:657)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:656)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
    at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:830)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:775)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90

**Comment by alexanderpann** [comment] 2022-10-07 11:35
I am closing because this is a duplicate of https://github.com/JetBrains/MPS-extensions/issues/355 and fixed in https://github.com/JetBrains/MPS-extensions/commit/d60a2f0cc2740d44a91379a9c80405d7624ffa8a.

**Closed by alexanderpann** 2022-10-07 11:35 UTC
