### ISSUE TITLE
de.itemis.mps.editor.diagram.runtime depends on both IDEA guava and q60 guava

### ISSUE THREAD

**Issue by enikao** [JetBrains/MPS-extensions#858] opened 2024-06-12 08:40 UTC
We're using `com.mbeddr.platform` version `2022.3-2022.3.24305.b0eebaa`.

`de.itemis.mps.editor.diagram.runtime.jgraph` uses `Multimap` from `de.q60.mps.collections.libs/com.google.common.collect`.

`de.itemis.mps.editor.diagram.runtime/org.eclipse.elk.*` uses `Multimap` from `MPS.IDEA/com.google.common.collect`.

Classloaders can get very confused by this.

**Comment by alexanderpann** [comment] 2024-06-14 08:20
The issue is fixed in #850. Let me know if there are still similar issues.

**Closed by alexanderpann** 2024-06-14 08:20 UTC

**Comment by enikao** [comment] 2024-06-17 07:23
Thanks @alexanderpann for the swift fix.
